# Generated by Django 3.1 on 2022-01-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('birth', models.DateField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('product', models.CharField(choices=[('생리대 중형', '생리대 중형'), ('생리대 대형', '생리대 대형'), ('탐폰 라이트', '탐폰 라이트'), ('탐폰 레귤러', '탐폰 레귤러'), ('탐폰 슈퍼', '탐폰 슈퍼')], max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
